# Generated by Django 2.0.5 on 2018-07-05 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_student_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('student_journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Журнал відвідування',
                'verbose_name_plural': 'Журнали відвідування',
            },
        ),
    ]
