# Generated by Django 2.0.5 on 2018-07-05 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20180705_2128'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='journal',
            unique_together={('student_journal', 'date')},
        ),
    ]
