# Generated by Django 2.0.5 on 2018-07-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.EmailField(max_length=236, unique=True, verbose_name='Email'),
        ),
    ]
