# Generated by Django 2.0.5 on 2018-07-10 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20180710_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examin',
            name='examin_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Group', verbose_name='Група'),
        ),
        migrations.AlterField(
            model_name='examin',
            name='examin_professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Professor', verbose_name='Викладач'),
        ),
    ]
