# Generated by Django 2.0.5 on 2018-09-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_auto_20180710_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_examin',
            field=models.ManyToManyField(through='students.ExaminResult', to='students.Examin', verbose_name='Екзамін'),
        ),
    ]
